### ISSUE TITLE
Super Mario Advance 1 audio beep

### ISSUE THREAD

**Issue by PenCapChew** [MiSTer-devel/GBA_MiSTer#100]
Hello,

I noticed while playing the first super mario advance game I hear an audible single beeping noise when entering doors or when the screen transitions, such as moving up a vine. I don't have the actual game to test on my gba at the moment but is this something that happens on real hardware or is it a possible glitch? I have the latest update of mister with original bios, and sync core to video option ON setting.

**Comment by RobertPeip** [comment]
This is very likely due to the "sync core to video"

Whenever the screen output gets delayed, which often happens on screen transitions/scenery change, the core is paused for up to 75% of a frame to be synced to video again, so modern screens don't desync. Pausing will hang the audio for that time, worst case up to ~10ms

You can try to set this off and use vsync_adjust=0 in your mister.ini

This will get you up 2 frames delay, but screen syncing isn't needed anymore. If the effect is gone, this was the reason.
If not, i would check against real GBA first.

**Comment by PenCapChew** [comment]
I forgot to mention I was using a vga crt as my display. I tried your suggestions vsync adjust set to zero. When I try to turn off "sync to video" to off in core settings my display becomes dark with the occasional flashing screen where it displays the game for a brief moment. I tested the game on an actual GBA and the issue is not present as well.

**Comment by RobertPeip** [comment]
VGA is using direct output without multiple buffers, so i has a hard requirement of using sync to video. Sorry can't do anything about that.
