### ISSUE TITLE
WarioWare Inc. - squares on sprites

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/GBA_MiSTer#20]
The bug appears in the Mona stage intro.
![square](https://user-images.githubusercontent.com/31185814/70340690-f2082f00-1859-11ea-913f-377d83cc436f.png)

Video of the bug mp4.
[ww bug video.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/3933161/ww.bug.video.zip)

Save file.
[WarioWare Inc. (U).sav.zip](https://github.com/MiSTer-devel/GBA_MiSTer/files/3933168/WarioWare.Inc.U.sav.zip)

**Comment by James-F2** [comment]
Also in that particular Mona demo, I see a single cloud flickering.
Maybe layer priority issue?

![cloud flicker](https://user-images.githubusercontent.com/31185814/70372209-d5fd9f80-18e4-11ea-8d73-97185bdcc57a.png)

**Comment by paulb-nl** [comment]
There are also other sprites that flicker and they all have in common that they are the last sprite in OAM.

The sprite data position is alternating every frame so first they are at the beginning of OAM and the next frame at the end. I assume that the sprite disappears when it's at the end of OAM. But there are other sprites that do not flicker which are the end of OAM so it is not just that.

Another issue is that the top of the dogs head during the intro disappears when it zooms in but I found the fix for that already.

**Comment by paulb-nl** [comment]
Finally figured it out. It happens when only the OBJ layer is enabled. 

gba_drawer_obj sets busy to 0 when it is done with OAMFetch and because there are no other layers the merging and clearing of the linebuffers begins. However the last pixel of sprite 126 and complete sprite 127 still have to be written but they are blocked because clearing has started.

**Comment by RobertPeip** [comment]
Great find Paul, thanks a lot. I don't see how this could fix this effects here, but i will fix the problem and we will see.

**Comment by RobertPeip** [comment]
i committed the fix, please recheck

**Comment by James-F2** [comment]
All fixed.
Amazing work Paul and Robert !
I'm closing this.
