### ISSUE TITLE
Zoom option?

### ISSUE THREAD

**Issue by shertz43** [MiSTer-devel/GBA_MiSTer#63]
On the Gameboy interface for the Gamecube using swiss, you have the option of zooming in the image to fill in the screen.  I hope this feature can be added to this MiSTer as well.  I am using the IO board with at RGB CRT at 480p.

BTW, the Gameboy LLAPI core works in full screen (no black boarders except a little bit on the left and right sides.)  For some reason the GBA LLAPI core has black boarders all arounf and is not full screen.

**Comment by MikeIronFist** [comment]
This is already possible if you use if you add a section to the end of your config file for GBA-specific settings.

Try something like:

```
[GBA]
vga_scaler=1
vscale_mode=0
video_mode=2
```
This will tell MiSTer to use the scaler on the analog output, just for the GBA core, disables forced integer scaling and sets the output resolution to 720x480p.

`vscale_mode=0` will fit the image to the maximum height it can reach without cutting off the sides, but since `video_mode=2` is 720x480 (standard 480p), it's actually a perfect 3x integer scale of the GBA's 240x160 resolution, so you should in theory get perfect full-screen GBA image, though some of the image can still be cut off by your CRT's overscan (if there is any overscan.)

If `video_mode=2` doesn't fit your CRT's horizontal resolution or looks wrong, you can use `video_mode=6` for 640x480 instead. If that still doesn't fill the screen to your liking, you can set the aspect ratio to 16:9 in the GBA core's menu to try and stretch the image horizontally.

If all of this is still not to your liking, you can even try custom video modes, like [this one I saw on reddit.](https://www.reddit.com/r/fpgagaming/comments/frg3nh/how_do_i_make_the_gba_core_full_screen_on_a_crt/flvs46l/) Results may vary.

**Comment by RobertPeip** [comment]
Please report back, otherwise i think this can be closed
