### ISSUE TITLE
Two 1536p Video Quirks

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [MiSTer-devel/GBA_MiSTer#71]
In 1535p, the video is shifted one row to the right (see below). Shifting it one row left should fix this.

Also, 1536p video_mode=13 results in black video drop outs (on the 1536p Apple display, and my Datapath Vision), but this custom mode works: video_mode=2048,48,32,170,1536,3,4,53,220056

![20200616_192019](https://user-images.githubusercontent.com/33355340/85192895-22a13a80-b279-11ea-9aea-e6f6aa9bc9bd.jpg)
![20200618_214438](https://user-images.githubusercontent.com/33355340/85192903-2765ee80-b279-11ea-8b0b-cda67b1dfe9b.jpg)

**Comment by sorgelig** [comment]
> In 1535p, the video is shifted one row to the right (see below). Shifting it one row left should fix this.

in 2048px mode (vertical resolution doesn't matter) there was roll over, but it was fixed in framework. So latest release should be free from this problem.



> Also, 1536p video_mode=13 results in black video drop outs (on the 1536p Apple display, and my Datapath Vision), but this custom mode works: video_mode=2048,48,32,170,1536,3,4,53,220056

220MHz is too much. If it works for you, then use this custom mode. Also use dvi_mode=1 which allows lower pixel clock due to narrower blanks (this is what video_mode=13 is tuned for).

**Comment by SmokeMonsterPacks** [comment]
Ahh, perfect, thank you!
