### ISSUE TITLE
Feature request: Add more steps to the "Modify Colors" option

### ISSUE THREAD

**Issue by plenilunium85** [MiSTer-devel/GBA_MiSTer#74]
It would be great if there were more steps in the "Modify Colors" option. Especially inbetween 100 to 75 percent. At least with my CRT color settings 100% is too much and 75% is already not colorful enough anymore. I know it's kinda picky because i could just edit the color settings on my CRT every time when i switch to the GBA core. Still it would be nice to have more options if it's not too much of a hassle to implement them. Also i don't see any difference between all the other options like GBA 2.2 or NDS 1.6 compared to "OFF".

**Comment by RobertPeip** [comment]
Options like GBA 2.2 or NDS 1.6 work, but make sure when you test them that you either disable "pause in OSD" or close the OSD, as the image will not get updated otherwise.

That said, i see now reason for color reduction settings, as the new color options are really good enough.

If you need anything else, try gamma settings next to the filters on second page in OSD
