### ISSUE TITLE
Mother 3 - Battles don't show / work?

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/GBA_MiSTer#80]
The game hangs and shows a single color when you get into a battle.  The first battle is about 10 minutes in after making a new game, after you dash into the dino.  I was using the translated rom, not sure if that had anything to do with the issue.

**Comment by RobertPeip** [comment]
Mother 3 was reported to work, so please provide more information:

- please upload a savestate right BEFORE the crash
- Hash of the ROM you are using, especially since it's nothing official
- Size of your SDRAM (you need 128Mbyte for this game or must switch to DDR3)
- Official BIOS or Homebrew BIOS (Normmatt)

**Comment by Aquas77** [comment]
Ah, I am using 32MB ram, would you like my continue my report?

**Comment by RobertPeip** [comment]
32MByte cannot work, as the game requires 32MByte and Workram/Saveram of the GBA some more.

Please set to DDR3 in OSD, save config and reboot the core and game before you try. It most likely works then.

**Comment by RobertPeip** [comment]
Any news on this one? Otherwise I will close, as 32Mbyte SDRam was most likely the problem.

**Comment by Aquas77** [comment]
Yes! Sorry about the delay, my bad. I switched to Storage: DDR3 and the battle works now. Thanks for the help!
