### ISSUE TITLE
Why does this core use so much logic?

### ISSUE THREAD

**Issue by charliehorse55** [MiSTer-devel/GBA_MiSTer#83]
I see in the description for https://github.com/RobertPeip/FPGBA that this cores uses ~37k LEs (assuming it didn't change substantially when coming to this repo). Where does this resource usage come from? A 32 bit RISC-V CPU with MMU and branch prediction is only ~3500 LEs. And yet this ARM core with neither is 13000? What is creating this complexity? Does any of it have to do with the added features? (that could be removed to save space). I'm very confused. 

 I'm trying to port this core to a low power, mobile FPGA, but the size is a big limiting factor right now. Any guidance or notes you can share would be extremely helpful!

**Comment by RobertPeip** [comment]
Ressource usage has changed quiet a lot since the first version(where this values come from).
On the De10-Nano we have a usage of:
35k LUTs and 29K FF

- CPU is 5800 LUTs. Keep in mind that even the older ARM23 core from opencores(used in Archie core) requires 4300 LUTs without having the newer ARM4 instruction and completly missing THUMB and Savestates. So i don't consider this a large size for such a 32Bit CPU.

- Largest Part is the 2D engine with 19k LUTs. Keep in mind that it is capable of doing 4 times the original resolution, so it could likely be less than 10k LUTs.

- DMA, Sound and Timers is each 1-2k LUTs and cannot be optimized much.

- You could remove overall ~10-20% when dropping the savestate feature.

If you really are interested in porting the core, you should tell which FPGA that is, so i could tell you if it's even worth a try.

Keep in mind that the memory usage(internal and external) is also one crucial part for the core. So i doubt small FPGA could filfill that need. It's currently 3Mbit with the chance to reduce that to ~1.5Mbit if you can bring the framebuffer/imagedata external.

**Comment by charliehorse55** [comment]
That makes sense, thanks for the info. 

We're aiming for the 40k LUT variant of lattice [Certus-NX](http://www.latticesemi.com/Products/FPGAandCPLD/Certus-NX). It has just under 3 Mbit of embedded memory. Why does the framebuffer take 1.5 Mbit? I see in the GBA documentation that the bitmap modes take up at most 655 kbit? Is that related to the extra resolution support on this core?

**Comment by RobertPeip** [comment]
There is one framebuffer for the output and another one for the frameblend feature. Also some memory is required by the MiSTer Framework and other features you might drop.

With this lattice FPGA you might get a very barebones GBA core. Meaning:
- no savestates/rewind
- no 2x rendering
- no flickerblend
- no colorshaders
- no 60FPS with fastforward

You maybe still have to optimize some parts for ressource usage.
E.g. 
- the 2D engine is made to be able to render at ~3 times speed without graphical glitches. (12 times in Hires mode!)
The ressource usage can be lower if drop such features.
- the CPU/Memory interfacing has 2 levels of caches for faster fastforward or faster CPU Turbomode

Keep in mind that the core was never designed with low ressource usage in mind. If I had the chance to improve or speed up the CPU/DMA/2D rendering/whatever at the cost of ressources, i will most likely always go that way, as my target platform had these ressources unused anyway.

Also make sure you have enough external RAM available on your board.
If you don't want the cache architecture, it also needs to be low latency.
You need 32Mbyte for the largest ROM + 256Kbyte for RAM and few hundred for Flash/EEprom.

**Comment by charliehorse55** [comment]
@RobertPeip Would you be interested in being paid to explain the code to me in a zoom call? I'm working on a commercial project and I'm sure it would save me a ton of time (vs. just stumbling around trying random things out).  ~2 hours of your time could probably save me multiple days. You can email me if you want to discuss this further.

**Comment by RobertPeip** [comment]
Keep in mind that with a commercial project, you have to fully disclose the source and all changes made to it because of the license. As you cannot port it to another platform without changes, it is impossible to not disclose your source code.
If you are aware of that and still want to do it, you can contact me.

**Comment by charliehorse55** [comment]
Yes, I understand the licensing requirements. How can I contact you? I didnt see any details on your github page?

**Comment by charliehorse55** [comment]
@RobertPeip

**Comment by RobertPeip** [comment]
I already sent an email to you 2 days ago to the address linked in your github profile.
Most likely my mail address is blocked from you, that happens sometimes unfortunatly, as it's my own webserver.

You can also reach me on
- twitter: https://twitter.com/AzumFpg 
- discord: FPGAzumSpass#0526
- skype. live:.cid.41a9a1adc1afc549
