### ISSUE TITLE
Metroid: Zero Mission - Intro holds on static instead of going to black screen

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/GBA_MiSTer#9]
Here's how it looks on a Game Boy Player:
https://streamable.com/xgw3j

Here's how it looks on MiSTer:
https://streamable.com/t7fv2

The static I'm talking about occurs about 23 seconds in, I'm thinking this has to do with the GBA turning the display off? Not sure though

**Comment by paulb-nl** [comment]
I looked into it a bit.  This is what I think happens: 
Metroid disables all layers (DISPCNT = 0000). In the core this disables drawing (draw_allmod = 00) and pixel_we stays low so the framebuffer is not updated and it retains the last written frame.

The core should output black pixels instead of stop drawing.

**Comment by RobertPeip** [comment]
Very good find and this will be an easy fix. I'll do it later today or tomorrow.
Thanks a lot Paul!

**Comment by MP2E** [comment]
@RobertPeip 's incoming fix addressed this issue, now it looks just like my Game Boy Player :) Closing!
